# Generated by Django 4.1.3 on 2022-11-19 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_remove_offerproperties_additional_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logotype', models.URLField()),
                ('deeplink_name', models.CharField(max_length=255)),
                ('salesmanager_hide', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rate_label', models.CharField(max_length=255)),
                ('rate_from', models.CharField(max_length=255)),
                ('rate_value', models.CharField(max_length=255)),
                ('rate_desc', models.CharField(max_length=255)),
                ('amount_label', models.CharField(max_length=255)),
                ('amount_to', models.CharField(max_length=255)),
                ('amount_value', models.CharField(max_length=255)),
                ('amount_desc', models.CharField(max_length=255)),
                ('term_label', models.CharField(max_length=255)),
                ('term_value', models.CharField(max_length=255)),
                ('term_desc', models.CharField(max_length=255)),
                ('info_line_0', models.CharField(max_length=255)),
                ('info_line_1', models.CharField(max_length=255)),
                ('info_line_2', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('additional_link', models.CharField(max_length=255)),
                ('btn_title', models.CharField(max_length=255)),
                ('special', models.CharField(max_length=255)),
                ('special_label', models.CharField(max_length=255)),
                ('visible', models.CharField(max_length=255)),
                ('loader', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('iframe_enable', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='OfferProperties',
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='Offer', max_length=120),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offers',
            field=models.ManyToManyField(to='offers.offerproperty'),
        ),
    ]
